//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace Family2Person.Persons
{
    
    
    /// <summary>
    /// The public interface for PersonRegister
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(PersonRegister))]
    [XmlDefaultImplementationTypeAttribute(typeof(PersonRegister))]
    [ModelRepresentationClassAttribute("platform:/plugin/Persons/model/Persons.ecore#//PersonRegister")]
    public interface IPersonRegister : IModelElement
    {
        
        /// <summary>
        /// The persons property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("persons")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("personsInverse")]
        [ConstantAttribute()]
        IOrderedSetExpression<IPerson> Persons
        {
            get;
        }
    }
}

